<div class="card"><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Rạp</label><select class="form-select" name="cinema_id">@foreach($cinemas as $cinema)<option value="{{ $cinema->id }}" @selected(old('cinema_id',$maintenanceRequest->cinema_id)==$cinema->id)>{{ $cinema->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Phòng</label><select class="form-select" name="auditorium_id"><option value="">Toàn rạp</option>@foreach($auditoriums as $auditorium)<option value="{{ $auditorium->id }}" @selected(old('auditorium_id',$maintenanceRequest->auditorium_id)==$auditorium->id)>{{ $auditorium->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Thiết bị</label><select class="form-select" name="equipment_id"><option value="">Không gắn thiết bị</option>@foreach($equipmentItems as $item)<option value="{{ $item->id }}" @selected(old('equipment_id',$maintenanceRequest->equipment_id)==$item->id)>{{ $item->name }}</option>@endforeach</select></div>
<div class="col-md-8"><label class="form-label">Tiêu đề</label><input class="form-control" name="title" value="{{ old('title',$maintenanceRequest->title) }}" required></div>
<div class="col-md-4"><label class="form-label">Người tạo</label><select class="form-select" name="requested_by"><option value="">Chọn nhân sự</option>@foreach($staffMembers as $member)<option value="{{ $member->id }}" @selected(old('requested_by',$maintenanceRequest->requested_by)==$member->id)>{{ $member->full_name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Ưu tiên</label><select class="form-select" name="priority">@foreach(['LOW','MEDIUM','HIGH','CRITICAL'] as $priority)<option value="{{ $priority }}" @selected(old('priority',$maintenanceRequest->priority ?: 'MEDIUM')===$priority)>{{ $priority }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Trạng thái</label><select class="form-select" name="status">@foreach(['OPEN','IN_PROGRESS','CLOSED','CANCELLED'] as $status)<option value="{{ $status }}" @selected(old('status',$maintenanceRequest->status ?: 'OPEN')===$status)>{{ $status }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Mở lúc</label><input type="datetime-local" class="form-control" name="opened_at" value="{{ old('opened_at',optional($maintenanceRequest->opened_at)->format('Y-m-d\TH:i')) }}"></div>
<div class="col-md-3"><label class="form-label">Đóng lúc</label><input type="datetime-local" class="form-control" name="closed_at" value="{{ old('closed_at',optional($maintenanceRequest->closed_at)->format('Y-m-d\TH:i')) }}"></div>
<div class="col-12"><label class="form-label">Mô tả</label><textarea class="form-control" rows="4" name="description">{{ old('description',$maintenanceRequest->description) }}</textarea></div>
</div></div><div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Lưu yêu cầu</button><a href="{{ route('admin.maintenance_requests.index') }}" class="btn btn-light-soft">Quay lại</a></div>
