<div class="card"><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Rạp</label><select class="form-select" name="cinema_id">@foreach($cinemas as $cinema)<option value="{{ $cinema->id }}" @selected(old('cinema_id',$equipment->cinema_id)==$cinema->id)>{{ $cinema->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Phòng chiếu</label><select class="form-select" name="auditorium_id"><option value="">Thiết bị chung toàn rạp</option>@foreach($auditoriums as $auditorium)<option value="{{ $auditorium->id }}" @selected(old('auditorium_id',$equipment->auditorium_id)==$auditorium->id)>{{ $auditorium->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Mã thiết bị</label><input class="form-control" name="code" value="{{ old('code',$equipment->code) }}" required></div>
<div class="col-md-5"><label class="form-label">Tên thiết bị</label><input class="form-control" name="name" value="{{ old('name',$equipment->name) }}" required></div>
<div class="col-md-3"><label class="form-label">Loại thiết bị</label><select class="form-select" name="equipment_type">@foreach(['PROJECTOR'=>'Máy chiếu','AUDIO'=>'Âm thanh','AIR_CONDITIONER'=>'Điều hoà','SCREEN'=>'Màn chiếu','LIGHTING'=>'Ánh sáng','OTHER'=>'Khác'] as $key=>$label)<option value="{{ $key }}" @selected(old('equipment_type',$equipment->equipment_type)===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Trạng thái</label><select class="form-select" name="status">@foreach(['ACTIVE','MAINTENANCE','BROKEN','RETIRED'] as $status)<option value="{{ $status }}" @selected(old('status',$equipment->status ?: 'ACTIVE')===$status)>{{ $status }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Ngày lắp đặt</label><input type="date" class="form-control" name="installed_at" value="{{ old('installed_at',optional($equipment->installed_at)->format('Y-m-d')) }}"></div>
</div></div><div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Lưu thiết bị</button><a href="{{ route('admin.equipment.index') }}" class="btn btn-light-soft">Quay lại</a></div>
