@extends('admin.layout')
@section('title', 'Chi tiết khách hàng')
@section('content')
<section class="page-header"><div><p class="eyebrow">Customer detail</p><h2>{{ $customer->full_name }}</h2><p>{{ $customer->phone ?: 'Chưa có SĐT' }} · {{ $customer->email ?: 'Chưa có email' }}</p></div><div class="d-flex gap-2"><a class="btn btn-primary" href="{{ route('admin.customers.edit',$customer) }}">Sửa</a><a class="btn btn-light-soft" href="{{ route('admin.customers.index') }}">Quay lại</a></div></section>
<<<<<<< HEAD
<div class="row g-3 mb-3">
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Thông tin thành viên</div><div><strong>Trạng thái:</strong> {{ $customer->account_status ?? 'ACTIVE' }}</div><div><strong>Điểm hiện có:</strong> {{ number_format($customer->loyaltyAccount?->points_balance ?? 0) }}</div><div><strong>Lifetime:</strong> {{ number_format($customer->loyaltyAccount?->lifetime_points ?? 0) }}</div><div><strong>Hạng:</strong> {{ $customer->loyaltyAccount?->tier?->name ?? 'Member' }}</div><div><strong>Tổng đã thanh toán:</strong> {{ number_format($paidAmount) }}đ</div><div><strong>Tổng hoàn tiền:</strong> {{ number_format($refundAmount) }}đ</div></div></div></div>
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Tài khoản đăng nhập</div>@if($customer->user)<div><strong>Tên hiển thị:</strong> {{ $customer->user->name }}</div><div><strong>Email đăng nhập:</strong> {{ $customer->user->email }}</div><div class="text-muted mt-2">Khách hàng này đã liên kết với tài khoản thành viên trên giao diện người dùng.</div>@else<div class="text-muted">Khách hàng hiện chưa liên kết với tài khoản user.</div>@endif</div></div></div>
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Phát sinh điểm gần đây</div>@forelse(($customer->loyaltyAccount?->transactions ?? collect())->sortByDesc('created_at')->take(5) as $txn)<div class="border rounded-4 p-2 mb-2"><div class="d-flex justify-content-between"><strong>{{ $txn->txn_type }}</strong><span>{{ $txn->points > 0 ? '+' : '' }}{{ number_format($txn->points) }}</span></div><div class="text-muted small">{{ $txn->note ?: 'Không có ghi chú' }}</div><div class="text-muted small">{{ optional($txn->created_at)->format('d/m/Y H:i') }}</div></div>@empty<div class="text-muted">Chưa có giao dịch điểm.</div>@endforelse</div></div></div>
</div>
<div class="card mb-3"><div class="card-body"><div class="fw-semibold mb-3">Lịch sử đặt vé</div>@forelse($customer->bookings as $booking)<div class="border rounded-4 p-3 mb-3"><div class="d-flex justify-content-between flex-wrap gap-2"><div><div class="list-primary">{{ $booking->booking_code }}</div><div class="list-secondary">{{ $booking->show?->movieVersion?->movie?->title ?? 'Suất chiếu' }} · {{ optional($booking->show?->start_time)->format('d/m/Y H:i') }}</div><div class="list-secondary">{{ $booking->show?->auditorium?->cinema?->name ?: 'FPL Cinema' }} · {{ $booking->show?->auditorium?->name ?: 'Phòng chiếu' }}</div></div><div class="text-end"><div class="fw-semibold">{{ number_format($booking->total_amount) }}đ</div><span class="badge badge-soft-primary">{{ $booking->status }}</span></div></div><div class="mt-2 list-secondary">Ghế: {{ $booking->tickets->pluck('seat.label')->filter()->implode(', ') ?: 'Chưa có' }}</div><div class="list-secondary">Combo: {{ $booking->bookingProducts->map(fn($item) => ($item->product?->name ?: 'Combo') . ' x' . $item->qty)->implode(', ') ?: 'Không có' }}</div><div class="list-secondary">Giảm giá: {{ $booking->discounts->map(function($item){ $label = $item->promotion?->name ?: ($item->coupon?->code ?: 'Khuyến mãi'); return $label . ' ' . number_format($item->discount_amount ?? 0) . 'đ'; })->implode(', ') ?: 'Không có' }}</div></div>@empty<div class="text-muted">Khách hàng chưa có booking.</div>@endforelse</div></div>
<div class="card"><div class="card-body"><div class="fw-semibold mb-3">Thanh toán & hoàn tiền</div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Mã giao dịch</th><th>Phương thức</th><th>Số tiền</th><th>Hoàn tiền</th><th>Trạng thái</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->external_txn_ref ?: '—' }}</td><td>{{ $payment->provider }} / {{ $payment->method }}</td><td>{{ number_format($payment->amount) }}đ</td><td>{{ number_format($payment->refunds->where('status','SUCCESS')->sum('amount')) }}đ</td><td>{{ $payment->status }}</td></tr>@empty<tr><td colspan="5" class="text-muted">Chưa có thanh toán.</td></tr>@endforelse</tbody></table></div></div></div>
=======
<div class="row g-3 mb-3"><div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Thông tin thành viên</div><div><strong>Trạng thái:</strong> {{ $customer->account_status ?? 'ACTIVE' }}</div><div><strong>Điểm hiện có:</strong> {{ number_format($customer->loyaltyAccount?->points_balance ?? 0) }}</div><div><strong>Lifetime:</strong> {{ number_format($customer->loyaltyAccount?->lifetime_points ?? 0) }}</div><div><strong>Tổng đã thanh toán:</strong> {{ number_format($paidAmount) }}đ</div><div><strong>Tổng hoàn tiền:</strong> {{ number_format($refundAmount) }}đ</div></div></div></div>
<div class="col-lg-8"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Lịch sử đặt vé</div>@forelse($customer->bookings as $booking)<div class="border rounded-4 p-3 mb-3"><div class="d-flex justify-content-between flex-wrap gap-2"><div><div class="list-primary">{{ $booking->booking_code }}</div><div class="list-secondary">{{ $booking->show?->movie?->title ?? 'Suất chiếu' }} · {{ optional($booking->show?->start_time)->format('d/m/Y H:i') }}</div></div><div class="text-end"><div class="fw-semibold">{{ number_format($booking->total_amount) }}đ</div><span class="badge badge-soft-primary">{{ $booking->status }}</span></div></div><div class="mt-2 list-secondary">Ghế: {{ $booking->tickets->pluck('seat.label')->filter()->implode(', ') ?: 'Chưa có' }}</div><div class="list-secondary">Combo: {{ $booking->bookingProducts->map(fn($item) => $item->product?->name . ' x' . $item->qty)->implode(', ') ?: 'Không có' }}</div><div class="list-secondary">Giảm giá: {{ $booking->discounts->map(fn($item) => ($item->discount_type ?? 'DISCOUNT') . ' ' . number_format($item->amount ?? 0) . 'đ')->implode(', ') ?: 'Không có' }}</div></div>@empty<div class="text-muted">Khách hàng chưa có booking.</div>@endforelse</div></div></div></div>
<div class="card"><div class="card-body"><div class="fw-semibold mb-3">Thanh toán & hoàn tiền</div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Mã giao dịch</th><th>Phương thức</th><th>Số tiền</th><th>Hoàn tiền</th><th>Trạng thái</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->external_txn_ref ?: '—' }}</td><td>{{ $payment->provider }} / {{ $payment->method }}</td><td>{{ number_format($payment->amount) }}đ</td><td>{{ number_format($payment->refunds->sum('amount')) }}đ</td><td>{{ $payment->status }}</td></tr>@empty<tr><td colspan="5" class="text-muted">Chưa có thanh toán.</td></tr>@endforelse</tbody></table></div></div></div>
>>>>>>> 64d8c448b79abac0443c5ccf39a8cc0d12ef3561
@endsection
