<div class="card"><div class="card-body row g-3">
<div class="col-md-4"><label class="form-label">Mã KM</label><input class="form-control" name="code" value="{{ old('code', $promotion->code) }}" required></div>
<div class="col-md-8"><label class="form-label">Tên khuyến mãi</label><input class="form-control" name="name" value="{{ old('name', $promotion->name) }}" required></div>
<div class="col-12"><label class="form-label">Mô tả</label><textarea class="form-control" rows="3" name="description">{{ old('description', $promotion->description) }}</textarea></div>
<div class="col-md-3"><label class="form-label">Kiểu giảm</label><select class="form-select" name="promo_type"><option value="AMOUNT" @selected(old('promo_type', $promotion->promo_type)=='AMOUNT')>Giảm tiền</option><option value="PERCENT" @selected(old('promo_type', $promotion->promo_type)=='PERCENT')>Giảm %</option></select></div>
<div class="col-md-3"><label class="form-label">Giá trị</label><input type="number" class="form-control" name="discount_value" value="{{ old('discount_value', $promotion->discount_value) }}" required></div>
<div class="col-md-3"><label class="form-label">Giảm tối đa</label><input type="number" class="form-control" name="max_discount_amount" value="{{ old('max_discount_amount', $promotion->max_discount_amount) }}"></div>
<div class="col-md-3"><label class="form-label">Đơn tối thiểu</label><input type="number" class="form-control" name="min_order_amount" value="{{ old('min_order_amount', $promotion->min_order_amount) }}"></div>
<div class="col-md-3"><label class="form-label">Áp dụng cho</label><select class="form-select" name="applies_to"><option value="ORDER">Toàn đơn</option><option value="TICKET">Vé</option><option value="PRODUCT">F&B</option></select></div>
<div class="col-md-3"><label class="form-label">Ngày bắt đầu</label><input type="datetime-local" class="form-control" name="start_at" value="{{ old('start_at', optional($promotion->start_at)->format('Y-m-d\TH:i')) }}" required></div>
<div class="col-md-3"><label class="form-label">Ngày kết thúc</label><input type="datetime-local" class="form-control" name="end_at" value="{{ old('end_at', optional($promotion->end_at)->format('Y-m-d\TH:i')) }}" required></div>
<div class="col-md-3"><label class="form-label">Trạng thái</label><select class="form-select" name="status"><option value="ACTIVE" @selected(old('status', $promotion->status)=='ACTIVE')>Active</option><option value="INACTIVE" @selected(old('status', $promotion->status)=='INACTIVE')>Inactive</option></select></div>
<div class="col-md-3"><label class="form-label">Thứ trong tuần</label><select class="form-select" name="day_of_week"><option value="">Mọi ngày</option>@foreach(($weekdays ?? [1=>'T2',2=>'T3',3=>'T4',4=>'T5',5=>'T6',6=>'T7',7=>'CN']) as $k=>$v)<option value="{{ $k }}" @selected((string)old('day_of_week', $promotion->day_of_week)===(string)$k)>{{ $v }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Giờ bắt đầu suất</label><input type="time" class="form-control" name="show_start_from" value="{{ old('show_start_from', $promotion->show_start_from) }}"></div>
<div class="col-md-3"><label class="form-label">Giờ kết thúc suất</label><input type="time" class="form-control" name="show_start_to" value="{{ old('show_start_to', $promotion->show_start_to) }}"></div>
<div class="col-md-3"><label class="form-label">Nhóm khách hàng</label><select class="form-select" name="customer_scope">@foreach($scopes as $value=>$label)<option value="{{ $value }}" @selected(old('customer_scope', $promotion->customer_scope ?: 'ALL')==$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Giới hạn tổng</label><input type="number" class="form-control" name="usage_limit_total" value="{{ old('usage_limit_total', $promotion->usage_limit_total) }}"></div>
<div class="col-md-3"><label class="form-label">Giới hạn/khách</label><input type="number" class="form-control" name="usage_limit_per_customer" value="{{ old('usage_limit_per_customer', $promotion->usage_limit_per_customer) }}"></div>
<div class="col-md-6"><label class="form-label">Áp dụng theo phim</label><select class="form-select" multiple name="movie_ids[]" size="6">@foreach($movies as $movie)<option value="{{ $movie->id }}" @selected(collect(old('movie_ids', $promotion->movies->pluck('id') ?? []))->contains($movie->id))>{{ $movie->title }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Áp dụng theo rạp</label><select class="form-select" multiple name="cinema_ids[]" size="6">@foreach($cinemas as $cinema)<option value="{{ $cinema->id }}" @selected(collect(old('cinema_ids', $promotion->cinemas->pluck('id') ?? []))->contains($cinema->id))>{{ $cinema->name }}</option>@endforeach</select></div>
<div class="col-md-3 form-check ms-3"><input class="form-check-input" type="checkbox" name="auto_apply" value="1" id="auto_apply" @checked(old('auto_apply', $promotion->auto_apply))><label class="form-check-label" for="auto_apply">Tự áp dụng theo rule</label></div>
<div class="col-md-3 form-check ms-3"><input class="form-check-input" type="checkbox" name="coupon_required" value="1" id="coupon_required" @checked(old('coupon_required', $promotion->coupon_required))><label class="form-check-label" for="coupon_required">Yêu cầu voucher</label></div>
<div class="col-md-3 form-check ms-3"><input class="form-check-input" type="checkbox" name="is_stackable" value="1" id="is_stackable" @checked(old('is_stackable', $promotion->is_stackable))><label class="form-check-label" for="is_stackable">Cho phép cộng dồn</label></div>
</div></div>
<div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Lưu khuyến mãi</button><a href="{{ route('admin.promotions.index') }}" class="btn btn-light-soft">Quay lại</a></div>
