@extends('admin.layout')
@section('title', 'Khuyến mãi')
@section('content')
<section class="page-header"><div><p class="eyebrow">Promotion</p><h2>Khuyến mãi / voucher</h2><p>Tạo mã giảm giá, rule tự động, giới hạn lượt dùng và theo dõi hiệu quả.</p></div><div class="d-flex gap-2"><a href="{{ route('admin.coupons.index') }}" class="btn btn-light-soft">Voucher</a><a href="{{ route('admin.promotions.create') }}" class="btn btn-primary">Tạo khuyến mãi</a></div></section>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="metric-card"><div class="metric-label">Đang active</div><div class="metric-value">{{ $summary['active'] }}</div></div></div><div class="col-md-3"><div class="metric-card"><div class="metric-label">Voucher rules</div><div class="metric-value">{{ $summary['voucher_count'] }}</div></div></div><div class="col-md-3"><div class="metric-card"><div class="metric-label">Giảm đã dùng</div><div class="metric-value">{{ number_format($summary['discount_total']) }}đ</div></div></div><div class="col-md-3"><div class="metric-card"><div class="metric-label">Auto apply</div><div class="metric-value">{{ $summary['auto_apply_count'] }}</div></div></div></div>
<div class="card toolbar-card mb-3"><div class="card-body"><form class="row g-3" method="GET"><div class="col-lg-9"><input class="form-control" name="q" value="{{ $q }}" placeholder="Tìm theo tên hoặc mã"></div><div class="col-lg-3"><button class="btn btn-primary w-100">Tìm</button></div></form></div></div>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Mã / tên</th><th>Loại</th><th>Phạm vi</th><th>Hiệu lực</th><th>Hiệu quả</th><th class="text-end">Thao tác</th></tr></thead><tbody>
@forelse($promotions as $promotion)
<tr><td><div class="list-primary">{{ $promotion->name }}</div><div class="list-secondary">{{ $promotion->code }}</div></td><td>{{ $promotion->promo_type === 'PERCENT' ? $promotion->discount_value.'%' : number_format($promotion->discount_value).'đ' }}</td><td>{{ $promotion->applies_to }}<div class="list-secondary">{{ $promotion->auto_apply ? 'Tự áp dụng' : 'Thủ công/voucher' }}</div></td><td>{{ optional($promotion->start_at)->format('d/m/Y H:i') }}<div class="list-secondary">đến {{ optional($promotion->end_at)->format('d/m/Y H:i') }}</div></td><td>{{ $promotion->booking_discounts_count }} lượt<div class="list-secondary">{{ $promotion->coupons_count }} voucher</div></td><td class="text-end"><div class="d-inline-flex gap-2"><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.promotions.show', $promotion) }}">Xem</a><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.promotions.edit', $promotion) }}">Sửa</a><form method="POST" action="{{ route('admin.promotions.destroy', $promotion) }}" onsubmit="return confirm('Xoá khuyến mãi này?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Xoá</button></form></div></td></tr>
@empty <tr><td colspan="6" class="empty-state">Chưa có khuyến mãi.</td></tr>@endforelse
</tbody></table></div><div class="card-body border-top">{{ $promotions->links() }}</div></div>
@endsection
