@extends('admin.layout')
@section('title', 'Chi tiết sản phẩm F&B')
@section('content')
<section class="page-header"><div><p class="eyebrow">F&B detail</p><h2>{{ $product->name }}</h2><p>{{ $product->sku }} · {{ $product->category?->name }}</p></div><div class="d-flex gap-2"><a href="{{ route('admin.products.edit', $product) }}" class="btn btn-primary">Sửa</a><a href="{{ route('admin.products.index') }}" class="btn btn-light-soft">Quay lại</a></div></section>
<div class="row g-3">
<div class="col-lg-4"><div class="card h-100"><div class="card-body">@if($product->attributes['image_url'] ?? null)<img src="{{ $product->attributes['image_url'] }}" alt="{{ $product->name }}" class="img-fluid rounded-4 border mb-3 w-100" style="max-height:240px;object-fit:cover;">@endif<div class="fw-semibold mb-2">Thông tin nhanh</div><div><strong>Loại:</strong> {{ $product->is_combo ? 'Combo' : 'Sản phẩm lẻ' }}</div><div><strong>Giá bán hiện hành:</strong> {{ $currentPrice ? number_format($currentPrice->price_amount).'đ' : 'Chưa có' }}</div><div><strong>Giá nhập gần nhất:</strong> {{ $purchaseStats['latest_cost'] !== null ? number_format($purchaseStats['latest_cost']).'đ' : 'Chưa có' }}</div><div><strong>Giá nhập TB:</strong> {{ $purchaseStats['avg_cost'] !== null ? number_format($purchaseStats['avg_cost']).'đ' : 'Chưa có' }}</div><div><strong>Đã bán:</strong> {{ number_format($soldQty) }}</div><div><strong>Doanh thu:</strong> {{ number_format($revenue) }}đ</div><div><strong>Lần nhập gần nhất:</strong> {{ $purchaseStats['last_received_at'] ? \Carbon\Carbon::parse($purchaseStats['last_received_at'])->format('d/m/Y H:i') : 'Chưa có' }}</div><div class="mt-3">{{ $product->attributes['description'] ?? 'Chưa có mô tả' }}</div></div></div></div>
<div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Tồn kho theo quầy/kho</div>@forelse($product->inventoryBalances as $balance)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $balance->stockLocation?->name }} · {{ $balance->stockLocation?->cinema?->name }}</span><span>{{ $balance->qty_on_hand }} / reorder {{ $balance->reorder_level }}</span></div>@empty<div class="text-muted">Chưa có tồn kho.</div>@endforelse</div></div></div>
<div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="fw-semibold mb-2">Lịch sử giá bán</div>@forelse($product->prices as $price)<div class="border-bottom py-2"><div>{{ number_format($price->price_amount) }}đ</div><div class="list-secondary">{{ $price->cinema?->name ?? 'Mặc định' }} · từ {{ optional($price->effective_from)->format('d/m/Y H:i') }}</div></div>@empty<div class="text-muted">Chưa có giá.</div>@endforelse</div></div></div>
</div>
<div class="card mt-3"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div class="fw-semibold">Lịch sử nhập / xuất gần đây</div><a href="{{ route('admin.inventory.movements', ['product_id' => $product->id]) }}" class="btn btn-sm btn-light-soft">Xem toàn bộ</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Thời gian</th><th>Vị trí</th><th>Biến động</th><th>Đơn giá</th><th>Nguồn</th><th>Ghi chú</th></tr></thead><tbody>@forelse($product->stockMovements as $movement)<tr><td>{{ optional($movement->created_at)->format('d/m/Y H:i') }}</td><td>{{ $movement->stockLocation?->name }} · {{ $movement->stockLocation?->cinema?->name }}</td><td>@if($movement->qty_delta > 0)<span class="badge badge-soft-success">+{{ number_format($movement->qty_delta) }}</span>@else<span class="badge badge-soft-danger">{{ number_format($movement->qty_delta) }}</span>@endif</td><td>{{ $movement->unit_cost_amount !== null ? number_format($movement->unit_cost_amount).'đ' : '—' }}</td><td>{{ $movement->reference_type ?: '—' }}</td><td>{{ $movement->note ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="empty-state">Chưa có biến động kho cho sản phẩm này.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
